esphome:
  name: abc

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
  
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  - platform: esphome
    password: !secret ota_pass

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ABC Fallback Hotspot"
    password: !secret fallback_hotspot_pass

captive_portal:

external_components:    
  - source:
      type: local
      path: components
    components: ["fallblatt_abc"]
  
text:
  - platform: fallblatt_abc
    id: "fallblatt_abc_1"
    name: "Fallblatt ABC"
    mode: "text"

  
