esphome:
  name: abc

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
  
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "1234"

ota:
  - platform: esphome
    password: "1234"

wifi:
  ssid: "Funk 2000"
  password: "50688917286037451494"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ABC Fallback Hotspot"
    password: "12345678"

captive_portal:

external_components:    
  - source:
      type: local
      path: components
    components: ["fallblatt_abc"]
  
text:
  - platform: fallblatt_abc
    id: "fallblatt_abc_1"
    name: "Fallblatt ABC"
    mode: "text"





  
